#redis配置
#Redis服务器地址
spring:
  redis:
    host: localhost
    post: 6379
    database: 0
    jedis:
      pool:
        max-active: 50
        max-wait: 3000
        max-idle: 20
        min-idle: 2
    timeout: 5000