package com.example.demo.repository;

import com.example.demo.entity.Person;
import com.example.demo.entity.PersonExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.data.rest.core.annotation.RestResource;
import org.springframework.stereotype.Service;

@Service
public interface PersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Wed Dec 25 15:45:03 GMT+08:00 2019
     */
    long countByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Wed Dec 25 15:45:03 GMT+08:00 2019
     */
    int deleteByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Wed Dec 25 15:45:03 GMT+08:00 2019
     */
    int insert(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Wed Dec 25 15:45:03 GMT+08:00 2019
     */
    int insertSelective(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Wed Dec 25 15:45:03 GMT+08:00 2019
     */
    @RestResource(path = "list")
    List<Person> selectByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Wed Dec 25 15:45:03 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") Person record, @Param("example") PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Wed Dec 25 15:45:03 GMT+08:00 2019
     */
    int updateByExample(@Param("record") Person record, @Param("example") PersonExample example);
}